on: push
name: Test, Build and Release APK
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.15'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.4'
      - run: flutter pub get
      - run: flutter create .
      - run: flutter run -d chrome
